apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: {{ .Values.apache.replicaCount }}
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
        ports:
        - containerPort: {{ .Values.apache.service.Port }}
